### ISSUE TITLE
please delete directory Ellona

### ISSUE THREAD

**Issue by eisoftserv** [iuandrei/csharp_selenium#1]
Bună!

Am încercat să-mi șterg sursele, deoarece nu am cum să șterg directory Ellona ... De ieri tot primesc acest mesaj când dau ”push”:
"The following errors were reported during push:
	refs/heads/master, protected branch hook declined"

Rugămintea mea este să ștergi directory Ellona de pe server (tu ca proprietar ai dreptul), ca să pot șterge acest repo de pe hard-discul meu.

Mulțumesc!

**Comment by iuandrei** [comment]
A ramas setat de ieri protectie pe master. Am scos protectia de pe master si ar trebui sa puteti face push acum.

**Comment by eisoftserv** [comment]
A mers ... mulțumesc!
